### ISSUE TITLE
How to train a single Lora with multiple people triggered by their names?

### ISSUE THREAD

**Issue by davidmartinrius** [ostris/ai-toolkit#108]
Hi there! I was wondering if it's possible to train a single LORA model to recognize and generate multiple specific faces or bodies of specific persons. For example, could one LORA model be used to generate both my own face and the faces of others based on their names? How to manage this with the trigger words?
I have a single dataset with all people tagged by its name and a short caption in the .txt files

**Comment by NBSTpeterhill** [comment]
please have some tries, and I mark here to wait an answer.

**Comment by davidmartinrius** [comment]
Hi, sorry, I don't get it @NBSTpeterhill what do you mean?

**Comment by NBSTpeterhill** [comment]
I also expect to get an answer, because many training parameters of ai-toolkit are not actually fully open.
So, I am curious too.

**Comment by bghira** [comment]
like this: https://huggingface.co/ptx0/flux-dreambooth-lora-r16-dev

**Comment by martintomov** [comment]
> For example, could one LORA model be used to generate both my own face and the faces of others based on their names? How to manage this with the trigger words?

You can train multiple triggers, each with its own set of images. The key is in the captions. Simply caption enough images of yourself using the trigger word associated with your face, and caption other images with the trigger word linked to whatever else you want to train. Repeat this for as much as wanted and find the limit, I think it should work.

**Comment by davidmartinrius** [comment]
You mean the trigger_word from .yaml file? 

So I should train a LoRA with a set of images of a person and a trigger. Then, do a fine-tuning of this LoRA with another set of images and another trigger, and so on? Doing fine-tunings repeatedly? Or can I train the model all at once with all the images and set up multiple triggers at the same time?

**Comment by davidmartinrius** [comment]
ok, the yaml file only allows one trigger word. So, how to specify multiple in the same training?
I already have a dataset like
people/David/image1.txt -> David in a suit and tie standing in front of a flag
people/David/image1.jpg
...
people/Martin/image1.txt -> Martin standing in front of a building
people/Martin/image1.jpg
...
people/PersonN/imageN.txt -> Name N doing something and wearing something bla bla
people/PersonN/imageN.jpg
...

And so on, each person has 100 images with its corresponding captions and each caption has the name of that person.

How to specify multiple triggers when training this?

**Comment by martintomov** [comment]
Give this a try:

1. Combine all images and captions into a single dataset folder.
2. Set the trigger word to something like “photograph” or “photograph style.”
3. For testing, use a learning rate of **4e-3** and set the steps to **1000**. (This is just for a quick validation to see if the idea works. Later, you should lower the learning rate and increase the steps for better results.)

**Comment by davidmartinrius** [comment]
Great @martintomov I am going to try it! You have clarified many doubts for me in a moment. Thank you so much!!

**Comment by martintomov** [comment]
No worries. I hope it works out well. I’m curious too, so I’ll share my results using this technique tomorrow.

**Comment by martintomov** [comment]
## @davidmartinrius, here’s what I found—results are a bit mixed:

I ran a quick test with 1000 steps and a learning rate of 4e-3 to see if this would work. The dataset had 8 images and captions for Person 1 and another 8 for Person 2. I gave each person a specific name in the dataset and manually captioned the images.  Trigger word: Photograph

#### Person 1:
<img src="https://github.com/user-attachments/assets/c0029825-f77d-43be-99a8-d5205765ca23" width="300">

#### Person 2:
<img src="https://github.com/user-attachments/assets/f9f407e7-66c8-43e5-911c-4bf94a7150ef" width="200">

# Results
### _Prompting each person separately:_

#### Person 1 output:
<img src="https://github.com/user-attachments/assets/d51d5335-c4f3-4ee5-a190-892bc95ea1c4" width="600">

#### Person 2 output:
<img src="https://github.com/user-attachments/assets/b4f37193-f1bf-407b-8454-ae66e5f9e1da" width="600">

### _Prompting them together:_

#### Output 1:
<img src="https://github.com/user-attachments/assets/bfcb4e37-c36f-417d-88b5-b671dda0b87f" width="600">

#### Output 2:
<img src="https://github.com/user-attachments/assets/9848b3bb-4451-4520-b521-c6340cebc501" width="600">

#### Output 3:
<img src="https://github.com/user-attachments/assets/81cc3f4c-bb28-45de-8d45-accbd7d2cf78" width="600">

# Conclusion

It's pretty interesting that prompting each person separately works flawlessly, but it struggles when you combine them. This might be due to the small dataset, too few training steps, or the learning rate being a bit too high. I’d suggest trying it again with a larger dataset, a learning rate of 1e-4, and around 4000 steps (or more?) to see if that improves things. Also, check out bghira’s model on Hugging Face—he shared a link in a comment above, and the results are worth a look: [Hugging Face - ptx0/flux-dreambooth-lora-r16-dev](https://huggingface.co/ptx0/flux-dreambooth-lora-r16-dev).

### Another approach to consider is LoRA Merging. I’ve found it to be pretty powerful, though I’m still exploring it:

#### Trained model on this dress:
<img src="https://github.com/user-attachments/assets/db626f08-58b4-4e45-a1e7-ee549f2b70b1" width="300">

#### Trained model on this face:
<img src="https://github.com/user-attachments/assets/17f71511-f208-4539-bd01-38c2ef3481d3" width="300">

#### LoRA Merging output:
<img src="https://github.com/user-attachments/assets/a34e4fe1-7e09-49c6-acd3-68f3ff799023" width="600">

**Comment by davidmartinrius** [comment]
I got bad results and I don't know why... maybe you could help me with this.

I used this dataset of 3 persons:
https://drive.google.com/file/d/1JLbaJbMJ_FRq4LXYrxyw4kzVYhHAT6gu/view?usp=drive_link

Each person has between 80-100 images. When training I just got blurry/noisy images like this one:

![1724112815056__000000750_4](https://github.com/user-attachments/assets/8475d08b-dbc1-49d8-bb62-4e7185c00e8c)

This is my config yaml

```
---
job: extension
config:
  # this name will be the folder and filename name
  name: "my_first_flux_lora_v1"
  process:
    - type: 'sd_trainer'
      # root folder to save training sessions/samples/weights
      training_folder: "output"
      # uncomment to see performance stats in the terminal every N steps
#      performance_log_every: 1000
      device: cuda:0
      # if a trigger word is specified, it will be added to captions of training data if it does not already exist
      # alternatively, in your captions you can add [trigger] and it will be replaced with the trigger word
      trigger_word: "photograph"
      network:
        type: "lora"
        linear: 16
        linear_alpha: 16
      save:
        dtype: float16 # precision to save
        save_every: 250 # save every this many steps
        max_step_saves_to_keep: 4 # how many intermittent saves to keep
      datasets:
        # datasets are a folder of images. captions need to be txt files with the same name as the image
        # for instance image2.jpg and image2.txt. Only jpg, jpeg, and png are supported currently
        # images will automatically be resized and bucketed into the resolution specified
        # on windows, escape back slashes with another backslash so
        # "C:\\path\\to\\images\\folder"
        - folder_path: "/workspace/ai-toolkit/dataset"
          caption_ext: "txt"
          caption_dropout_rate: 0.05  # will drop out the caption 5% of time
          shuffle_tokens: false  # shuffle caption order, split by commas
          cache_latents_to_disk: true  # leave this true unless you know what you're doing
          resolution: [ 512, 768, 1024 ]  # flux enjoys multiple resolutions
      train:
        batch_size: 1
        steps: 1000  # total number of steps to train 500 - 4000 is a good range
        gradient_accumulation_steps: 1
        train_unet: true
        train_text_encoder: false  # probably won't work with flux
        gradient_checkpointing: true  # need the on unless you have a ton of vram
        noise_scheduler: "flowmatch" # for training only
        optimizer: "adamw8bit"
        lr: 4e-3
        # uncomment this to skip the pre training sample
#        skip_first_sample: true
        # uncomment to completely disable sampling
#        disable_sampling: true
        # uncomment to use new vell curved weighting. Experimental but may produce better results
#        linear_timesteps: true

        # ema will smooth out learning, but could slow it down. Recommended to leave on.
        ema_config:
          use_ema: true
          ema_decay: 0.99

        # will probably need this if gpu supports it for flux, other dtypes may not work correctly
        dtype: bf16
      model:
        # huggingface model name or path
        name_or_path: "black-forest-labs/FLUX.1-dev"
        is_flux: true
        quantize: true  # run 8bit mixed precision
#        low_vram: true  # uncomment this if the GPU is connected to your monitors. It will use less vram to quantize, but is slower.
      sample:
        sampler: "flowmatch" # must match train.noise_scheduler
        sample_every: 250 # sample every this many steps
        width: 1024
        height: 1024
        prompts:
          # you can add [trigger] to the prompts here and it will be replaced with the trigger word
#          - "[trigger] holding a sign that says 'I LOVE PROMPTS!'"\
          - "a [trigger] of Carles Puigdemont with red hair, playing chess at the park, bomb going off in the background"
          - "a [trigger] of Rey Felipe holding a coffee cup, in a beanie, sitting at a cafe"
          - "a [trigger] of Reina Leticia as a DJ at a night club, fish eye lens, smoke machine, lazer lights, holding a martini"
          - "Photograph of Carles Puigdemont and Reina Leticia eating cake at a restaurant"
          - "a [trigger] of Rey Felipe with a bear disguise in a log cabin in the snow covered mountains"
          - "Reina Leticia playing the guitar, on stage, singing a song, laser lights, punk rocker"
          - "Rey Felipe with a beard, building a chair, in a wood shop"
          - "photograph of Carles Puigdemont, white background, medium shot, modeling clothing, studio lighting, white backdrop"
          - "a photograph of Rey Felipe holding a sign that says, 'I am the fucking king' as a gangsta in LA"
          - "a [trigger] of Carles Puigdemont, in a post apocalyptic world, with a shotgun, in a leather jacket, in a desert, with a motorcycle"
        neg: ""  # not used on flux
        seed: 42
        walk_seed: true
        guidance_scale: 4
        sample_steps: 20
# you can add any additional meta info here. [name] is replaced with config name at top
meta:
  name: "[name]"
  version: '1.0'
```
