### ISSUE TITLE
How to use locally downloaded models？

### ISSUE THREAD

**Issue by dzy1128** [ostris/ai-toolkit#121]
Running  1 process
Loading Flux model
Loading transformer
Error running job: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like /data/sdweb/ComfyUI/models/unet/transformer is not the path to a directory containing a config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.

========================================
Result:
 - 0 completed jobs
 - 1 failure
========================================
Traceback (most recent call last):
  File "/data/sdweb/ai-toolkit/venv/lib/python3.11/site-packages/diffusers/configuration_utils.py", line 379, in load_config
    config_file = hf_hub_download(
                  ^^^^^^^^^^^^^^^^
  File "/data/sdweb/ai-toolkit/venv/lib/python3.11/site-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/data/sdweb/ai-toolkit/venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "/data/sdweb/ai-toolkit/venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/data/sdweb/ComfyUI/models/unet/transformer'. Use `repo_type` argument if needed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/sdweb/ai-toolkit/run.py", line 90, in <module>
    main()
  File "/data/sdweb/ai-toolkit/run.py", line 86, in main
    raise e
  File "/data/sdweb/ai-toolkit/run.py", line 78, in main
    job.run()
  File "/data/sdweb/ai-toolkit/jobs/ExtensionJob.py", line 22, in run
    process.run()
  File "/data/sdweb/ai-toolkit/jobs/process/BaseSDTrainProcess.py", line 1230, in run
    self.sd.load_model()
  File "/data/sdweb/ai-toolkit/toolkit/stable_diffusion_model.py", line 487, in load_model
    transformer = FluxTransformer2DModel.from_pretrained(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/sdweb/ai-toolkit/venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/data/sdweb/ai-toolkit/venv/lib/python3.11/site-packages/diffusers/models/modeling_utils.py", line 612, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
                                         ^^^^^^^^^^^^^^^^
  File "/data/sdweb/ai-toolkit/venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/data/sdweb/ai-toolkit/venv/lib/python3.11/site-packages/diffusers/configuration_utils.py", line 415, in load_config
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like /data/sdweb/ComfyUI/models/unet/transformer is not the path to a directory containing a config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.

# huggingface model name or path
name_or_path: "/data/sdweb/ComfyUI/models/unet" #Absolute path of the local model
Here are the contents of the unet folder：
![unet](https://github.com/user-attachments/assets/185969e3-d9e4-4a91-93de-774ea0ee5d5b)

**Comment by martintomov** [comment]
## Check #84

**Comment by dzy1128** [comment]
> ## Check #84

Thank you very much for your answer, but I wrote absolute path in name_or_path and it still gives me an error, it will add /transformer after the path:
![image](https://github.com/user-attachments/assets/a297215a-ad15-41b6-9e44-948d4f9db748)
![image](https://github.com/user-attachments/assets/429c58ef-d3d1-45c1-880f-ff9bbfc93c1d)

**Comment by KW-0330** [comment]
I had the similar problem few hours ago. Since it is getting the model from Hugging face, I will need a token acquired from HF, and permit everything except the billing. I need to put the key under the root folder as well.

**Comment by dzy1128** [comment]
> I had the similar problem few hours ago. Since it is getting the model from Hugging face, I will need a token acquired from HF, and permit everything except the billing. I need to put the key under the root folder as well.

I can get the models from HF successfully,but the download speed is too slow.

**Comment by KW-0330** [comment]
Same here, took me few hours

**Comment by martintomov** [comment]
> > ## Check #84
> 
> 
> 
> Thank you very much for your answer, but I wrote absolute path in name_or_path and it still gives me an error, it will add /transformer after the path:
> 
> ![image](https://github.com/user-attachments/assets/a297215a-ad15-41b6-9e44-948d4f9db748)
> 
> ![image](https://github.com/user-attachments/assets/429c58ef-d3d1-45c1-880f-ff9bbfc93c1d)
> 
> 

the absolute path would mean cloning the whole flux repository, not just the models. so you need to 'git clone https://huggingface.co/black-forest-labs/FLUX.1-dev'.

**Comment by tcla75** [comment]
> > > ## Check #84
> > 
> > 
> > Thank you very much for your answer, but I wrote absolute path in name_or_path and it still gives me an error, it will add /transformer after the path:
> > ![image](https://private-user-images.githubusercontent.com/82308593/360725000-a297215a-ad15-41b6-9e44-948d4f9db748.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MDkyNjEsIm5iZiI6MTcyNDQwODk2MSwicGF0aCI6Ii84MjMwODU5My8zNjA3MjUwMDAtYTI5NzIxNWEtYWQxNS00MWI2LTllNDQtOTQ4ZDRmOWRiNzQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDEwMjkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjMmQ1ZTFkMzYwZTA3NWQ3MDUzYzYyNGRlZWI0MmE2NGExZDlkYjUxM2JlZDI1ZTIzYWU5ZjJlMzg3NmMzMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d3KVbuUbGCsQvSOc87zMtqJnLynusq9Won5lmylwlgM)
> > ![image](https://private-user-images.githubusercontent.com/82308593/360725141-429c58ef-d3d1-45c1-880f-ff9bbfc93c1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MDkyNjEsIm5iZiI6MTcyNDQwODk2MSwicGF0aCI6Ii84MjMwODU5My8zNjA3MjUxNDEtNDI5YzU4ZWYtZDNkMS00NWMxLTg4MGYtZmY5YmJmYzkzYzFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDEwMjkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwYmU1NTcyYjE2ODkzOTA1OWQyMDc2MjA0OGJjM2YzMTc5ZGFhNzQwMTlkMDEwZmRkOTllMDE0OTU0OGQ2N2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HUM6uRID3_eJGkGZB9MWuCy_PMF9OXp_kbvMjeEB3aE)
> 
> the absolute path would mean cloning the whole flux repository, not just the models. so you need to `git clone https://huggingface.co/black-forest-labs/FLUX.1-dev`

Did you try git clone https://huggingface.co/black-forest-labs/FLUX.1-dev before posting that answer here? because that doesn't work for me. it asks for my huggingface username and password which then gives the following error 

Password authentication in git is no longer supported. You must use a user access token or an SSH key instead. See https://huggingface.co/blog/password-git-deprecation
fatal: Authentication failed for 'https://huggingface.co/black-forest-labs/FLUX.1-dev/'


I followed the guide here https://huggingface.co/blog/password-git-deprecation and it is now downloading for me

**Comment by martintomov** [comment]
> 
> 
> 
> 
> 
> 
> > > > ## Check #84
> 
> > > 
> 
> > > 
> 
> > > Thank you very much for your answer, but I wrote absolute path in name_or_path and it still gives me an error, it will add /transformer after the path:
> 
> > > ![image](https://private-user-images.githubusercontent.com/82308593/360725000-a297215a-ad15-41b6-9e44-948d4f9db748.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MDkyNjEsIm5iZiI6MTcyNDQwODk2MSwicGF0aCI6Ii84MjMwODU5My8zNjA3MjUwMDAtYTI5NzIxNWEtYWQxNS00MWI2LTllNDQtOTQ4ZDRmOWRiNzQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDEwMjkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjMmQ1ZTFkMzYwZTA3NWQ3MDUzYzYyNGRlZWI0MmE2NGExZDlkYjUxM2JlZDI1ZTIzYWU5ZjJlMzg3NmMzMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d3KVbuUbGCsQvSOc87zMtqJnLynusq9Won5lmylwlgM)
> 
> > > ![image](https://private-user-images.githubusercontent.com/82308593/360725141-429c58ef-d3d1-45c1-880f-ff9bbfc93c1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MDkyNjEsIm5iZiI6MTcyNDQwODk2MSwicGF0aCI6Ii84MjMwODU5My8zNjA3MjUxNDEtNDI5YzU4ZWYtZDNkMS00NWMxLTg4MGYtZmY5YmJmYzkzYzFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDEwMjkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwYmU1NTcyYjE2ODkzOTA1OWQyMDc2MjA0OGJjM2YzMTc5ZGFhNzQwMTlkMDEwZmRkOTllMDE0OTU0OGQ2N2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HUM6uRID3_eJGkGZB9MWuCy_PMF9OXp_kbvMjeEB3aE)
> 
> > 
> 
> > the absolute path would mean cloning the whole flux repository, not just the models. so you need to `git clone https://huggingface.co/black-forest-labs/FLUX.1-dev`
> 
> 
> 
> Did you try git clone https://huggingface.co/black-forest-labs/FLUX.1-dev before posting that answer here? because that doesn't work for me. it asks for my huggingface username and password which then gives the following error 
> 
> 
> 
> Password authentication in git is no longer supported. You must use a user access token or an SSH key instead. See https://huggingface.co/blog/password-git-deprecation
> 
> fatal: Authentication failed for 'https://huggingface.co/black-forest-labs/FLUX.1-dev/'
> 
> 
> 
> 
> 
> I followed the guide here https://huggingface.co/blog/password-git-deprecation and it is now downloading for me

of course i tried it, the error message is self explanatory really. you need to enter your hugging face username and your access token (not password). READ access token should can be generated from https://huggingface.co/settings/tokens

**Comment by Virtike** [comment]
I'm having similar issues. I cannot get ai-toolkit to download the Flux repository - it downloads 400MB or so of pytorch_model-00001-of-00003.safetensors then download speed drops to 0kb/s and it fails/hangs.

```
Loading Flux model
Loading transformer
(…)pytorch_model-00001-of-00003.safetensors:   0%|                                         | 0.00/9.98G [00:00<?, ?B/s]
```

So, I tried cloning the entire black-forest-labs/FLUX.1-dev repository, but now run into a different problem:
```
Running  1 process
Loading Flux model
Loading transformer
An error occurred while trying to fetch C:\Apps\ai-toolkit\FLUX\transformer: Error no file named diffusion_pytorch_model.safetensors found in directory C:\Apps\ai-toolkit\FLUX\transformer.
Error running job: Error no file named diffusion_pytorch_model.bin found in directory C:\Apps\ai-toolkit\FLUX\transformer.
```
As per https://huggingface.co/black-forest-labs/FLUX.1-dev/tree/main/transformer there is no "diffusion_pytorch_model.bin" or "diffusion_pytorch_model.safetensors" - instead there is diffusion_pytorch_model split across 3x safetensors.

![image](https://github.com/user-attachments/assets/307c3d18-44cf-4a3c-8c49-1c642613cd48)

**Comment by tcla75** [comment]
> > > > > ## Check #84
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Thank you very much for your answer, but I wrote absolute path in name_or_path and it still gives me an error, it will add /transformer after the path:
> > 
> > 
> > > > ![image](https://private-user-images.githubusercontent.com/82308593/360725000-a297215a-ad15-41b6-9e44-948d4f9db748.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MDkyNjEsIm5iZiI6MTcyNDQwODk2MSwicGF0aCI6Ii84MjMwODU5My8zNjA3MjUwMDAtYTI5NzIxNWEtYWQxNS00MWI2LTllNDQtOTQ4ZDRmOWRiNzQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDEwMjkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjMmQ1ZTFkMzYwZTA3NWQ3MDUzYzYyNGRlZWI0MmE2NGExZDlkYjUxM2JlZDI1ZTIzYWU5ZjJlMzg3NmMzMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d3KVbuUbGCsQvSOc87zMtqJnLynusq9Won5lmylwlgM)
> > 
> > 
> > > > ![image](https://private-user-images.githubusercontent.com/82308593/360725141-429c58ef-d3d1-45c1-880f-ff9bbfc93c1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MDkyNjEsIm5iZiI6MTcyNDQwODk2MSwicGF0aCI6Ii84MjMwODU5My8zNjA3MjUxNDEtNDI5YzU4ZWYtZDNkMS00NWMxLTg4MGYtZmY5YmJmYzkzYzFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDEwMjkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwYmU1NTcyYjE2ODkzOTA1OWQyMDc2MjA0OGJjM2YzMTc5ZGFhNzQwMTlkMDEwZmRkOTllMDE0OTU0OGQ2N2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HUM6uRID3_eJGkGZB9MWuCy_PMF9OXp_kbvMjeEB3aE)
> > 
> > 
> > > 
> > 
> > 
> > > the absolute path would mean cloning the whole flux repository, not just the models. so you need to `git clone https://huggingface.co/black-forest-labs/FLUX.1-dev`
> > 
> > 
> > Did you try git clone https://huggingface.co/black-forest-labs/FLUX.1-dev before posting that answer here? because that doesn't work for me. it asks for my huggingface username and password which then gives the following error
> > Password authentication in git is no longer supported. You must use a user access token or an SSH key instead. See https://huggingface.co/blog/password-git-deprecation
> > fatal: Authentication failed for 'https://huggingface.co/black-forest-labs/FLUX.1-dev/'
> > I followed the guide here https://huggingface.co/blog/password-git-deprecation and it is now downloading for me
> 
> of course i tried it, the error message is self explanatory really. you need to enter your hugging face username and your access token (not password). READ access token can be generated from https://huggingface.co/settings/tokens

so after you downloaded it what exactly did you put in the name_or_path in the yaml file. As someone here has already said there is no one file for the absolute path so did you put in C:\SD\training\ai-toolkit\New folder\FLUX.1-dev or C:\SD\training\ai-toolkit\New folder\FLUX.1-dev\transformer or did you copy as path one of the files?

**Comment by martintomov** [comment]
> I'm having similar issues. I cannot get ai-toolkit to download the Flux repository - it downloads 400MB or so of pytorch_model-00001-of-00003.safetensors then download speed drops to 0kb/s and it fails/hangs.
> 
> 
> 
> ```
> 
> Loading Flux model
> 
> Loading transformer
> 
> (…)pytorch_model-00001-of-00003.safetensors:   0%|                                         | 0.00/9.98G [00:00<?, ?B/s]
> 
> ```
> 
> 
> 
> So, I tried cloning the entire black-forest-labs/FLUX.1-dev repository, but now run into a different problem:
> 
> ```
> 
> Running  1 process
> 
> Loading Flux model
> 
> Loading transformer
> 
> An error occurred while trying to fetch C:\Apps\ai-toolkit\FLUX\transformer: Error no file named diffusion_pytorch_model.safetensors found in directory C:\Apps\ai-toolkit\FLUX\transformer.
> 
> Error running job: Error no file named diffusion_pytorch_model.bin found in directory C:\Apps\ai-toolkit\FLUX\transformer.
> 
> ```
> 
> As per https://huggingface.co/black-forest-labs/FLUX.1-dev/tree/main/transformer there is no "diffusion_pytorch_model.bin" or "diffusion_pytorch_model.safetensors" - instead there is diffusion_pytorch_model split across 3x safetensors.
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/307c3d18-44cf-4a3c-8c49-1c642613cd48)
> 
> 

...

> so after you downloaded it what exactly did you put in the name_or_path in the yaml file. As someone here has already said there is no one file for the absolute path so did you put in C:\SD\training\ai-toolkit\New folder\FLUX.1-dev or C:\SD\training\ai-toolkit\New folder\FLUX.1-dev\transformer or did you copy as path one of the files?

as i said, clone the FLUX.1 repository. the path shouldn't lead to /transformers but to the WHOLE repository.

here is one of my configs that uses local model path, hope it resolves your questions...:

```
{
job: extension
config:
  name: rayban-meta-4000-v2
  process:
  - type: sd_trainer
    training_folder: output
    performance_log_every: 1000
    device: cuda:0
    trigger_word: Ray-Ban Meta Smart Glasses
    network:
      type: lora
      linear: 32
      linear_alpha: 32
    save:
      dtype: float16
      save_every: 250
      max_step_saves_to_keep: 4
    datasets:
    - folder_path: C:\...\dataset
      caption_ext: txt
      caption_dropout_rate: 0.05
      shuffle_tokens: false
      cache_latents_to_disk: true
      resolution:
      - 512
      - 768
      - 1024
    train:
      batch_size: 1
      steps: 4000
      gradient_accumulation_steps: 1
      train_unet: true
      train_text_encoder: false
      gradient_checkpointing: true
      noise_scheduler: flowmatch
      optimizer: adamw8bit
      lr: 0.0002
      linear_timesteps: true
      ema_config:
        use_ema: true
        ema_decay: 0.99
      dtype: bf16
    model:
      name_or_path: C:\...\ai-toolkit\FLUX.1-dev
      is_flux: true
      quantize: true
    sample:
      sampler: flowmatch
      sample_every: 250
      width: 1024
      height: 1024
      prompts:
      - Ray-Ban Meta Smart Glasses, close-up photograph, woman looking up, long blonde
        hair, wearing black-framed glasses, light pink lips, wearing gold earrings,
        navy blue background
      - a woman holding a coffee cup, in a beanie, wearing Ray-Ban Meta Smart Glasses,
        sitting at a cafe
      - a a DJ at a night club, fish eye lens, wearing Ray-Ban Meta Smart Glasses,
        smoke machine, lazer lights, holding a martini
      - a man showing off his cool new t shirt at the beach, wearing Ray-Ban Meta
        Smart Glasses, a shark is jumping out of the water in the background
      - a man wearing Ray-Ban Meta Smart Glasses, in snow covered mountains
      - close up of a man, wearing Ray-Ban Meta Smart Glasses, in a coffee shop, holding
        a cup, smiling
      - Ray-Ban Meta Smart Glasses, close-up photograph, wearing black-framed yellow-tinted
        sunglasses, short brown hair, slight smile, clear blue sky with clouds in
        the background.
      - photo of a man, wearing Ray-Ban Meta Smart Glasses, white background, medium
        shot, modeling clothing, studio lighting, white backdrop
      - a man holding a sign that says, 'Do these glasses fit me?', wearing Ray-Ban
        Meta Smart Glasses
      - Ray-Ban Meta Smart Glasses, close-up of a man adjusting glasses, photograph,
        partial side angle, wearing a green knit beanie and green jacket with visible
        stitching and button, short beard and mustache, silver earring in left ear,
        background features out-of-focus light colors
      neg: ''
      seed: 42
      walk_seed: true
      guidance_scale: 4
      sample_steps: 20
meta:
  name: rayban-meta-4000-v2
  version: '1.0'
}
```

**Comment by Virtike** [comment]
> > so after you downloaded it what exactly did you put in the name_or_path in the yaml file. As someone here has already said there is no one file for the absolute path so did you put in C:\SD\training\ai-toolkit\New folder\FLUX.1-dev or C:\SD\training\ai-toolkit\New folder\FLUX.1-dev\transformer or did you copy as path one of the files?
> 
> the path shouldn't lead to /transformer but to the WHOLE repository.
Yep, base path for the repository, not just transfomer
```
model:
        # huggingface model name or path
        # name_or_path: "black-forest-labs/FLUX.1-dev"
        name_or_path: "C:\\Apps\\ai-toolkit\\FLUX"
        is_flux: true
        quantize: true  # run 8bit mixed precision
```
![image](https://github.com/user-attachments/assets/42b95abc-c9cb-4c45-a955-0588cbbef16e)
So it finds the /transformer path, but not the expected files.
