### ISSUE TITLE
can i run this on RTS 4070Ti Super 16g Vram ? 

### ISSUE THREAD

**Issue by ahmederaqi95** [ostris/ai-toolkit#148]
can i run this on RTS 4070Ti Super 16g Vram ?

**Comment by an303042** [comment]
while the readme says its 24gb vram only, I ran it on a 4080 Super with 16gb VRAM (and 64gb ram on the mobo), and as far as i can tell the lora came out well

**Comment by bishwashadhikari1** [comment]
@an303042  brother how were you able to do it, mine  is stuck at generating image  0%  0/10 from the first while generating baseline samples before training.

**Comment by thesby** [comment]
So 16G vram is ok to train? Could you please paste your configs? lora size, batch size and other parameters.

**Comment by bishwashadhikari1** [comment]
@thesby  it is possible just takes way too much time (8-20 hrs) for optimal results. You can try the settings you would use on 24G vram.

**Comment by bishwashadhikari1** [comment]
This is exactly what i used, you will start getting decent results after 3000 steps.
This setup took me about 12 hours to complete on 4080 Super 16GB VRAM
```
---
job: extension
config:
  # this name will be the folder and filename name
  name: "bishwash_v1.2"
  process:
    - type: 'sd_trainer'
      # root folder to save training sessions/samples/weights
      training_folder: "output/bishwash"
      # uncomment to see performance stats in the terminal every N steps
      performance_log_every: 500
      device: cuda:0
      # if a trigger word is specified, it will be added to captions of training data if it does not already exist
      # alternatively, in your captions you can add [trigger] and it will be replaced with the trigger word
      trigger_word: "bishwash"
      network:
        type: "lora"
        linear: 32
        linear_alpha: 32
      save:
        dtype: float16 # precision to save
        save_every: 400 # save every this many steps
        max_step_saves_to_keep: 8 # how many intermittent saves to keep
        push_to_hub: false #change this to True to push your trained model to Hugging Face.
        # You can either set up a HF_TOKEN env variable or you'll be prompted to log-in         
#       hf_repo_id: your-username/your-model-slug
#       hf_private: true #whether the repo is private or public
      datasets:
        # datasets are a folder of images. captions need to be txt files with the same name as the image
        # for instance image2.jpg and image2.txt. Only jpg, jpeg, and png are supported currently
        # images will automatically be resized and bucketed into the resolution specified
        # on windows, escape back slashes with another backslash so
        # "C:\\path\\to\\images\\folder"
        - folder_path: "C:/Users/WOO/Desktop/workspace/2024/test1/ai-toolkit/bishwash_dataset/v1"
          caption_ext: "txt"
          caption_dropout_rate: 0.05  # will drop out the caption 5% of time
          shuffle_tokens: false  # shuffle caption order, split by commas
          cache_latents_to_disk: true  # leave this true unless you know what you're doing
          resolution: [ 512, 768, 1024 ]  # flux enjoys multiple resolutions
      train:
        batch_size: 1
        steps: 5000  # total number of steps to train 500 - 4000 is a good range
        gradient_accumulation_steps: 1
        train_unet: true
        train_text_encoder: false  # probably won't work with flux
        gradient_checkpointing: true  # need the on unless you have a ton of vram
        noise_scheduler: "flowmatch" # for training only
        optimizer: "adamw8bit"
        lr: 1e-4
        # uncomment this to skip the pre training sample
        skip_first_sample: true
        # uncomment to completely disable sampling
#        disable_sampling: true
        # uncomment to use new vell curved weighting. Experimental but may produce better results
#        linear_timesteps: true

        # ema will smooth out learning, but could slow it down. Recommended to leave on.
        ema_config:
          use_ema: true
          ema_decay: 0.99

        # will probably need this if gpu supports it for flux, other dtypes may not work correctly
        dtype: bf16
      model:
        # huggingface model name or path
        name_or_path: "black-forest-labs/FLUX.1-dev"
        is_flux: true
        quantize: true  # run 8bit mixed precision
        low_vram: true  # uncomment this if the GPU is connected to your monitors. It will use less vram to quantize, but is slower.
      sample:
        sampler: "flowmatch" # must match train.noise_scheduler
        sample_every: 200 # sample every this many steps
        width: 1024
        height: 1024
        prompts:
          # you can add [trigger] to the prompts here and it will be replaced with the trigger word
        - "[trigger] holding a sign that says 'I LOVE PROMPTS!' with a proud expression, standing on a busy street corner."
        - "[trigger] with bright red hair, playing an intense game of chess at a park, a bomb going off in the background, mid-explosion."
        - "[trigger] holding a coffee cup, wearing a beanie, sitting at a cozy cafe table, gazing out the window with a relaxed vibe."
        - "[trigger] is a DJ at a night club, fish-eye lens view, smoke filling the air, laser lights flashing, holding a martini while mixing tracks."
        - "[trigger] showing off their cool new t-shirt on a sunny beach, as a shark jumps out of the water in the background, waves crashing."
        - "[trigger] training alone in an empty gym, wearing headphones, focused on lifting weights with determination in a quiet setting."
        - "[trigger] playing the guitar on stage, belting out a song with passion, surrounded by laser lights, giving off a punk rocker vibe."
        - "[trigger] with a beard, hard at work building a chair in a woodshop, surrounded by tools, sawdust flying in the air."
        - "[trigger] posing in front of a white background, medium shot, modeling a stylish outfit under bright studio lighting, white backdrop behind."
        - "[trigger] in a post-apocalyptic world, gripping a shotgun, wearing a leather jacket, standing in a barren desert next to a motorcycle, ready for action."
        neg: ""  # not used on flux
        seed: 42
        walk_seed: true
        guidance_scale: 4
        sample_steps: 20
# you can add any additional meta info here. [name] is replaced with config name at top
meta:
  name: "[bishwash_v1.1]"
  version: '1.0'
```
