### ISSUE TITLE
[Question] How to adapt generate.example.yaml to use a Lora ?

### ISSUE THREAD

**Issue by IronTurp** [ostris/ai-toolkit#72]
I have trained a Lora using the train_lora_flux.yaml file, but I can't seem to be able to find a way to use generate to test it on the fly. I'd like to avoid ComfyUI for now. Any pointers ?

**Comment by MaximClouser** [comment]
Hi did you solve this? If so, how did you do it?

**Comment by moeinheidari7829** [comment]
Same questions here. Can you mention how you solved it?

**Comment by mbesenzoni** [comment]
``` yaml
model:
   name_or_path: "<base model>"
   lora_path: "<path to folder containing .safetensor files>"
```

couldn't find any documentation on this, had to dig through code
